import sys
import random
import re
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from config.settings import SKIN_CONCERNS, SKIN_GOALS, SKIN_TYPES
from services.profile_service import (
    get_user_profile,
    normalize_profile,
    normalize_user_id,
    profile_exists,
    save_user_profile,
)
from utils.helpers import highlight_concerns, skin_type_badge, skin_type_description


def generate_profile_id(name: str) -> str:
    name_part = re.sub(r"\s+", "_", name.strip()) if name.strip() else "user"
    name_part = re.sub(r"[^A-Za-z0-9_-]", "", name_part) or "user"
    return normalize_user_id(f"{name_part}_{random.randint(1000, 9999)}")


def load_profile_into_session(profile_id: str) -> bool:
    saved_profile = get_user_profile(profile_id)
    if not saved_profile:
        return False

    st.session_state.user_profile = saved_profile
    st.session_state.profile_user_id = saved_profile["user_id"]
    st.session_state.profile_name_input = saved_profile.get("name", "")
    st.session_state.profile_id_input = saved_profile["user_id"]
    st.session_state.profile_id_autogenerated = False
    st.session_state.routine_mode = saved_profile.get("routine_mode")
    st.session_state.routine = saved_profile.get("routine", [])
    st.session_state.ar_days = saved_profile.get("ar_days", {})
    st.session_state.editing_profile = False
    st.session_state.creating_profile = False
    st.session_state.profile_storage_status = "loaded"
    return True


def on_profile_name_change():
    if not st.session_state.get("profile_id_autogenerated", True):
        return
    st.session_state.profile_id_input = generate_profile_id(
        st.session_state.get("profile_name_input", "")
    )


def on_profile_id_change():
    st.session_state.profile_id_autogenerated = False


def show_storage_status():
    storage_status = st.session_state.pop("profile_storage_status", None)
    if storage_status == "saved":
        st.success("Profile saved to Cloud SQL.")
    if storage_status == "loaded":
        st.success("Profile loaded.")
    if storage_status == "logged_out":
        st.success("Logged out.")


def logout_profile():
    """Clear the loaded profile and related in-session user context."""
    for key in (
        "profile_name_input",
        "profile_id_input",
        "profile_id_autogenerated",
        "load_profile_id",
        "routine_search",
        "routine_search_results",
        "routine_last_search",
        "adding_product",
        "show_product_details",
        "chat_messages",
        "chat_thread_id",
        "chat_shortcuts_hidden",
        "pending_shortcut",
        "interested_products",
    ):
        st.session_state.pop(key, None)

    st.session_state.user_profile = {}
    st.session_state.profile_user_id = "default"
    st.session_state.editing_profile = False
    st.session_state.creating_profile = False
    st.session_state.routine_mode = None
    st.session_state.routine = []
    st.session_state.ar_days = {}
    st.session_state.profile_storage_status = "logged_out"


def show_profile_entry():
    st.title("👤 Profile")
    show_storage_status()
    st.markdown("### Are you a first-time user?")

    first_time, returning = st.columns(2)
    with first_time:
        with st.container(border=True):
            st.markdown("#### First time user")
            st.caption("Create a profile and save it to Cloud SQL with your own profile ID.")
            if st.button("Create a new profile", type="primary", use_container_width=True):
                st.session_state.creating_profile = True
                st.session_state.editing_profile = True
                st.session_state.profile_id_autogenerated = True
                st.session_state.profile_name_input = ""
                st.session_state.profile_id_input = generate_profile_id("")
                st.rerun()

    with returning:
        with st.container(border=True):
            st.markdown("#### Returning user")
            load_id = st.text_input(
                "Profile ID",
                key="load_profile_id",
                placeholder="e.g. amy_1234",
                help="Load a profile saved in Cloud SQL.",
            )
            if st.button("Load profile", use_container_width=True):
                if load_profile_into_session(load_id):
                    st.rerun()
                else:
                    st.warning("No saved profile found for that ID.")


def show_profile_form():
    profile = st.session_state.get("user_profile", {})
    is_edit = bool(profile.get("skin_type"))

    st.title("✏️ Edit Profile" if is_edit else "👤 Create Your Skin Profile")
    show_storage_status()
    if not is_edit:
        st.markdown("Tell us about your skin so we can personalise your experience.")

    if "profile_name_input" not in st.session_state:
        st.session_state.profile_name_input = profile.get("name", "")
    if "profile_id_input" not in st.session_state:
        st.session_state.profile_id_input = profile.get("user_id") or generate_profile_id(
            st.session_state.profile_name_input
        )
    if "profile_id_autogenerated" not in st.session_state:
        st.session_state.profile_id_autogenerated = not bool(profile.get("user_id"))

    st.subheader("Basic Info")
    col1, col2 = st.columns(2)
    with col1:
        name = st.text_input(
            "Your name",
            key="profile_name_input",
            placeholder="e.g. Amy",
            on_change=on_profile_name_change,
        )
    with col2:
        user_id_input = st.text_input(
            "Profile ID",
            key="profile_id_input",
            disabled=is_edit,
            help=(
                "Generated from your name with four random digits. You can change it before saving."
                if not is_edit
                else "Profile IDs cannot be changed after the profile has been created."
            ),
            on_change=on_profile_id_change,
        )

    with st.form("profile_form"):
        age_options = ["Prefer not to say", "Under 18", "18–24", "25–34", "35–44", "45–54", "55+"]
        age_range = st.selectbox(
            "Age range",
            age_options,
            index=age_options.index(profile.get("age_range", "Prefer not to say")),
        )

        st.divider()
        st.subheader("Skin Type")
        current_skin = profile.get("skin_type", SKIN_TYPES[0])
        skin_idx = SKIN_TYPES.index(current_skin) if current_skin in SKIN_TYPES else 0
        skin_type = st.radio(
            "Skin type",
            SKIN_TYPES,
            index=skin_idx,
            horizontal=True,
            label_visibility="collapsed",
        )
        sensitive_skin = st.checkbox(
            "Sensitive or reactive skin",
            value=bool(profile.get("sensitive_skin") or current_skin == "Sensitive"),
        )

        st.divider()
        st.subheader("Skin Concerns")
        selected_concerns = st.multiselect(
            "What are your main skin concerns?",
            SKIN_CONCERNS,
            default=profile.get("concerns", []),
        )

        st.divider()
        st.subheader("Skincare Goals")
        selected_goals = st.multiselect(
            "What are you trying to achieve?",
            SKIN_GOALS,
            default=profile.get("goals", []),
            help="These help the advisor tailor recommendations to what you actually want.",
        )

        st.divider()
        st.subheader("Notes")
        profile_notes = st.text_area(
            "Anything else you want the advisor to know?",
            value=profile.get("notes", ""),
            placeholder=(
                "e.g. I prefer simple routines, I am currently pregnant, "
                "my skin reacts badly to strong actives."
            ),
            height=120,
            help="Saved with your profile and included in chat context.",
        )

        # st.divider()
        # st.subheader("Ingredient Preferences")
        # col_a, col_b = st.columns(2)
        # with col_a:
        #     st.markdown("**Avoid:**")
        #     avoid_fragrance = st.checkbox("Fragrance / Parfum", value=profile.get("avoid_fragrance", False))
        #     avoid_alcohol = st.checkbox("Drying Alcohols", value=profile.get("avoid_alcohol", False))
        #     avoid_parabens = st.checkbox("Parabens", value=profile.get("avoid_parabens", False))
        #     avoid_silicones = st.checkbox("Silicones", value=profile.get("avoid_silicones", False))
        # with col_b:
        #     st.markdown("**Prefer:**")
        #     pref_vegan = st.checkbox("Vegan", value=profile.get("pref_vegan", False))
        #     pref_cruelty_free = st.checkbox("Cruelty-free", value=profile.get("pref_cruelty_free", False))
        #     pref_reef_safe = st.checkbox("Reef-safe", value=profile.get("pref_reef_safe", False))

        # st.divider()
        # st.subheader("Known Allergens")
        # allergens_input = st.text_area(
        #     "Ingredients you react to (one per line)",
        #     value="\n".join(profile.get("allergens", [])),
        #     placeholder="e.g.\nNiacinamide\nRetinol",
        #     height=100,
        # )

        avoid_fragrance = profile.get("avoid_fragrance", False)
        avoid_alcohol = profile.get("avoid_alcohol", False)
        avoid_parabens = profile.get("avoid_parabens", False)
        avoid_silicones = profile.get("avoid_silicones", False)
        pref_vegan = profile.get("pref_vegan", False)
        pref_cruelty_free = profile.get("pref_cruelty_free", False)
        pref_reef_safe = profile.get("pref_reef_safe", False)
        allergens_input = "\n".join(profile.get("allergens", []))

        submitted = st.form_submit_button(
            "Save Profile", type="primary", use_container_width=True
        )

    if submitted:
        allergens = [a.strip() for a in allergens_input.splitlines() if a.strip()]
        user_id = normalize_user_id(user_id_input)
        existing_user_id = normalize_user_id(profile.get("user_id"))
        is_new_profile = not bool(profile.get("skin_type")) or st.session_state.get("creating_profile", False)
        if is_new_profile and profile_exists(user_id):
            st.error("That profile ID is already in use. Change the Profile ID and save again.")
            return

        if not is_new_profile and user_id != existing_user_id and profile_exists(user_id):
            st.error("That profile ID is already in use. Change the Profile ID and save again.")
            return

        saved_profile = normalize_profile({
            "user_id": user_id,
            "name": name,
            "age_range": age_range,
            "skin_type": skin_type,
            "sensitive_skin": sensitive_skin,
            "concerns": selected_concerns,
            "goals": selected_goals,
            "notes": profile_notes.strip(),
            "avoid_fragrance": avoid_fragrance,
            "avoid_alcohol": avoid_alcohol,
            "avoid_parabens": avoid_parabens,
            "avoid_silicones": avoid_silicones,
            "pref_vegan": pref_vegan,
            "pref_cruelty_free": pref_cruelty_free,
            "pref_reef_safe": pref_reef_safe,
            "allergens": allergens,
            "routine_mode": st.session_state.get("routine_mode") or profile.get("routine_mode"),
            "routine": st.session_state.get("routine", profile.get("routine", [])),
            "ar_days": st.session_state.get("ar_days", profile.get("ar_days", {})),
        })
        if save_user_profile(user_id, saved_profile):
            st.session_state.user_profile = saved_profile
            st.session_state.profile_user_id = user_id
            st.session_state.editing_profile = False
            st.session_state.creating_profile = False
            st.session_state.profile_storage_status = "saved"
            st.rerun()
        else:
            st.error("Could not save your profile to Cloud SQL. Check the database connection and try again.")


def show_profile_view():
    profile = st.session_state.user_profile
    name = profile.get("name", "")
    show_storage_status()

    col_title, col_edit, col_logout = st.columns([5, 1, 1])
    with col_title:
        st.title(f"👤 Hi, {name}!" if name else "👤 Your Skin Profile")
        if profile.get("user_id"):
            st.caption(f"Profile ID: `{profile['user_id']}`")
    with col_edit:
        st.write("")
        if st.button("Edit", use_container_width=True, type="primary"):
            st.session_state.profile_name_input = profile.get("name", "")
            st.session_state.profile_id_input = profile.get("user_id", "")
            st.session_state.profile_id_autogenerated = False
            st.session_state.editing_profile = True
            st.rerun()
    with col_logout:
        st.write("")
        if st.button("Log out", use_container_width=True):
            logout_profile()
            st.rerun()

    skin_type = profile.get("skin_type", "")
    st.markdown(f"### {skin_type_badge(skin_type)} {skin_type} Skin")
    st.caption(skin_type_description(skin_type))

    if profile.get("age_range") and profile["age_range"] != "Prefer not to say":
        st.caption(f"Age range: {profile['age_range']}")
    if profile.get("sensitive_skin"):
        st.caption("Sensitive or reactive skin")

    concerns = profile.get("concerns", [])
    if concerns:
        st.divider()
        st.subheader("Skin Concerns")
        st.markdown(highlight_concerns(concerns), unsafe_allow_html=True)
        st.write("")

    goals = profile.get("goals", [])
    if goals:
        st.divider()
        st.subheader("Goals")
        st.markdown(
            " ".join(
                f'<span style="background:#e8f5e9;color:#2e7d32;padding:2px 8px;'
                f'border-radius:12px;margin:2px;font-size:0.8rem">{g}</span>'
                for g in goals
            ),
            unsafe_allow_html=True,
        )
        st.write("")

    notes = str(profile.get("notes") or "").strip()
    if notes:
        st.divider()
        st.subheader("Notes")
        st.write(notes)

    flags = []
    if profile.get("avoid_fragrance"):
        flags.append("🌿 Fragrance-free")
    if profile.get("avoid_alcohol"):
        flags.append("🚫 Alcohol-free")
    if profile.get("avoid_parabens"):
        flags.append("✅ Paraben-free")
    if profile.get("avoid_silicones"):
        flags.append("🔵 Silicone-free")
    if profile.get("pref_vegan"):
        flags.append("🌱 Vegan")
    if profile.get("pref_cruelty_free"):
        flags.append("🐰 Cruelty-free")
    if profile.get("pref_reef_safe"):
        flags.append("🐠 Reef-safe")

    if flags:
        st.divider()
        st.subheader("Preferences")
        cols = st.columns(min(len(flags), 4))
        for i, flag in enumerate(flags):
            with cols[i % 4]:
                st.markdown(f"`{flag}`")

    allergens = profile.get("allergens", [])
    if allergens:
        st.divider()
        st.subheader("Known Allergens")
        for a in allergens:
            st.markdown(f"- {a}")


# ── Init session state ─────────────────────────────────────────────────────────
if "user_profile" not in st.session_state:
    st.session_state.user_profile = {}
if "editing_profile" not in st.session_state:
    st.session_state.editing_profile = False
if "profile_user_id" not in st.session_state:
    st.session_state.profile_user_id = st.session_state.user_profile.get("user_id", "default")
if "creating_profile" not in st.session_state:
    st.session_state.creating_profile = False

has_profile = bool(st.session_state.user_profile.get("skin_type"))

if not has_profile and not st.session_state.editing_profile:
    show_profile_entry()
elif not has_profile or st.session_state.editing_profile:
    if has_profile and st.session_state.editing_profile:
        if st.button("← Back"):
            st.session_state.editing_profile = False
            st.rerun()
    show_profile_form()
else:
    show_profile_view()
